# Unified Configuration for netssh-rs Workspace
# This file contains configuration for all crates in the workspace

# Global settings that apply to all crates
[global]
log_level = "info"
environment = "development"  # Options: "development", "staging", "production"
default_timeout_seconds = 30

# Scheduler Configuration
[scheduler]
enabled = true

[scheduler.database]
url = "sqlite:scheduler.db"
max_connections = 10

[scheduler.server]
host = "127.0.0.1"
port = 8080

[scheduler.worker]
concurrency = 4
timeout_seconds = 300
connection_reuse = true
max_idle_time_seconds = 300
max_connections_per_worker = 10
failure_strategy = "continue"  # Options: "continue", "abort_first", "abort_after_n"
failure_strategy_n = 3  # Only used when failure_strategy = "abort_after_n"

[scheduler.board]
enabled = true
ui_path = "/board"
api_prefix = "/board/api"
auth_enabled = false

[scheduler.logging]
level = "info"
# file = "scheduler.log"  # Uncomment to enable file logging
# format = "json"  # Use "json" for structured logging, "text" for human-readable (default)
# rotation = "daily"  # File rotation: "daily", "hourly", "never" (default: daily)

[scheduler.scheduler]
enabled = true
poll_interval_seconds = 30
timezone = "UTC"
max_concurrent_jobs = 10

# netssh-core Configuration - Comprehensive settings from settings.json
[netssh.network]
# Network-related timeout settings control all network I/O operations
tcp_connect_timeout_secs = 60  # Timeout for establishing TCP connections
tcp_read_timeout_secs = 30     # Timeout for reading data from TCP sockets
tcp_write_timeout_secs = 30    # Timeout for writing data to TCP sockets
default_ssh_port = 22          # Default SSH port to use when none is specified
command_response_timeout_secs = 30  # Maximum time to wait for a response after sending a command
pattern_match_timeout_secs = 20     # Maximum time to wait for a pattern match when reading output
command_exec_delay_ms = 100         # Short delay between sending a command and starting to read the response
retry_delay_ms = 1000              # Delay between retry attempts in milliseconds
max_retry_attempts = 3             # Maximum number of retry attempts for operations that support retrying
device_operation_timeout_secs = 120 # Timeout for device-specific operations that might take longer

[netssh.ssh]
# SSH-specific settings control the SSH protocol operations
blocking_timeout_secs = 1      # Timeout for all blocking libssh2 function calls (read/write/auth/etc). Set to 0 for no timeout.
auth_timeout_secs = 30         # Timeout for SSH authentication operations
keepalive_interval_secs = 60   # Interval for sending SSH keepalive packets
channel_open_timeout_secs = 20 # Timeout for opening SSH channels

[netssh.buffer]
# Buffer settings control memory usage for I/O operations
read_buffer_size = 65536       # Default read buffer size in bytes (64KB)
buffer_pool_size = 32          # Maximum number of buffers to keep in the buffer pool
buffer_reuse_threshold = 16384 # Buffers smaller than this will be reused, larger ones will be allocated (16KB)
auto_clear_buffer = true       # Whether to automatically clear the buffer before sending commands

[netssh.concurrency]
# Concurrency settings control parallel connection handling
max_connections = 100                    # Maximum number of concurrent connections allowed
permit_acquire_timeout_ms = 5000        # Timeout for acquiring a connection permit in milliseconds
connection_idle_timeout_secs = 300      # How long a connection can remain idle before being closed

[netssh.logging]
# Logging settings control debug and session logging
enable_session_log = false     # Whether to enable session logging (records all SSH session activity)
session_log_path = "logs"      # Path to the session log directory (logs are stored with timestamp and session ID)
log_binary_data = false        # Whether to log binary data (increases log size but useful for debugging binary protocols)

[netssh.security]
strict_host_key_checking = true
known_hosts_file = "~/.ssh/known_hosts"
max_auth_attempts = 3

# TextFSM Configuration (for netssh-textfsm crate)
[textfsm]
template_cache_size = 1000
parsing_timeout_seconds = 10
template_directories = ["templates/", "/usr/share/textfsm/"]
enable_caching = true

# Python Integration Configuration (for netssh-python crate)
[python]
enabled = true
max_workers = 4
timeout_seconds = 300
virtual_env_path = ""  # Optional: path to Python virtual environment

# API Configuration (for future netssh-api crate)
[api]
enabled = false
host = "127.0.0.1"
port = 3000
rate_limit_requests_per_minute = 1000
cors_enabled = true
cors_origins = ["*"]
auth_required = false

[api.logging]
access_log = true
error_log = true
performance_log = true

# Development and Testing Configuration
[development]
mock_ssh_connections = false
test_data_directory = "test_data/"
enable_debug_endpoints = true

[testing]
parallel_test_execution = true
test_timeout_seconds = 60
cleanup_test_data = true

# Production-specific settings
[production]
strict_error_handling = true
performance_monitoring = true
health_check_interval_seconds = 30
