refresh_rate: 30 seconds

appenders:
  info_file:
    kind: rolling_file
    path: "logs/info.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} [{l}] {t} - {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 50mb
      roller:
        kind: fixed_window
        pattern: logs/info.{}.log
        count: 5
        base: 1

  debug_file:
    kind: rolling_file
    path: "logs/debug.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} [{l}] {t} - {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 50mb
      roller:
        kind: fixed_window
        pattern: logs/debug.{}.log
        count: 5
        base: 1

  session_file:
    kind: rolling_file
    path: "logs/session.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} [{l}] {t} - {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 50mb
      roller:
        kind: fixed_window
        pattern: logs/session.{}.log
        count: 5
        base: 1

  console:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} [{h({l})}] {t} - {m}{n}"

root:
  level: info
  appenders:
    - console
    - info_file

loggers:
  netmiko_rs::debug:
    level: off
    appenders:
      - debug_file
    additive: false

  netmiko_rs::session:
    level: off
    appenders:
      - session_file
    additive: false
